version: '2'
services:
  zk:
    image: zookeeper
    ports:
      - 2181:2181
  kafka:
    image: confluentinc/cp-kafka
    ports:
      - 9092:9092
      - 9999:9999
    links:
      - zk
    environment:
      JMX_PORT: 9999
      KAFKA_ZOOKEEPER_CONNECT: zk:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  influxdb:
    image: influxdb
    ports:
      - 8086:8086
  kafka-admin:
    image: orangemi/kafka-admin
    container_name: kakfa-admin
    environment:
      KAFKA_ADMIN_zookeeper: zk:2181
      KAFKA_ADMIN_KAFKA: kafka:2181
    links:
      - zk:zk
      - kafka:kafka
      - influxdb:influxdb
    ports:
      - 9001:9001

